### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deniuscoder** [chuyik/brackets-snippets#12]
Does not work after the update release 1.6.3
Does not start with the program brackets

**Comment by chuyik** [comment]
Hi could you offer more details?
You could open `Debug` -> `Show Developer Tools` and paste the errors to here.

**Comment by deniuscoder** [comment]
Exception in 'activeEditorChange' listener on Object TypeError: object is not a function TypeError: object is not a function
    at activeEditorChangeHandler (file:///C:/Users/Denius/AppData/Roaming/Brackets/extensions/user/edc.brackets-snippets/main.js:37:18)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1081:29)
    at Pane.trigger (/utils/EventDispatcher.js:222:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:729:14)
    at Pane.showView (/view/Pane.js:1011:14)
    at _showEditor (/editor/EditorManager.js:557:14)
/utils/EventDispatcher.js:225 Assertion failed:

**Comment by chuyik** [comment]
:joy: Someone has reported this error before, but I could not reproduce it. Maybe you could try to uninstall and reinstall the extension.

**Comment by deniuscoder** [comment]
When was version 1.6.2 it worked fine

**Comment by deniuscoder** [comment]
Exception in 'activeEditorChange' listener on Object {_eventHandlers: Object, on: function, off: function, one: function, trigger: function…}_EventDispatcher: true_createFullEditorForDocument: function _createFullEditorForDocument(document, pane) {arguments: (...)get arguments: function ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeErrorconstructor: function ThrowTypeError() { [native code] }__proto__: Object__proto__: function Empty() {}<function scope>set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 2name: "_createFullEditorForDocument"prototype: _createFullEditorForDocument__proto__: function Empty() {}<function scope>_createUnattachedMasterEditor: function _createUnattachedMasterEditor(doc) {_eventHandlers: Object_notifyActiveEditorChanged: function _notifyActiveEditorChanged(current) {_saveEditorViewState: function _saveEditorViewState(editor) {canOpenPath: function canOpenPath(fullPath) {closeInlineWidget: function closeInlineWidget(hostEditor, inlineWidget) {createInlineEditorForDocument: function createInlineEditorForDocument(doc, range, inlineContent) {focusEditor: function focusEditor() {getActiveEditor: function getActiveEditor() {getCurrentFullEditor: function getCurrentFullEditor() {getCurrentlyViewedPath: function getCurrentlyViewedPath() {getFocusedEditor: function getFocusedEditor() {getFocusedInlineWidget: function getFocusedInlineWidget() {getInlineEditors: function getInlineEditors(hostEditor) {off: function (events, fn) {on: function (events, fn) {one: function (events, fn) {openDocument: function openDocument(doc, pane) {registerCustomViewer: function registerCustomViewer() {registerInlineDocsProvider: function registerInlineDocsProvider(provider, priority) {registerInlineEditProvider: function registerInlineEditProvider(provider, priority) {registerJumpToDefProvider: function registerJumpToDefProvider(provider) {resizeEditor: function resizeEditor() {setEditorHolder: function setEditorHolder() {trigger: function (eventName) {__proto__: Object TypeError: object is not a function TypeError: object is not a function
    at activeEditorChangeHandler (file:///C:/Users/Denius/AppData/Roaming/Brackets/extensions/user/edc.brackets-snippets/main.js:37:18)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1081:29)
    at Pane.trigger (/utils/EventDispatcher.js:222:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:729:14)
    at Pane.showView (/view/Pane.js:1011:14)
    at _showEditor (/editor/EditorManager.js:557:14)/utils/EventDispatcher.js:224 trigger/editor/EditorManager.js:165 _notifyActiveEditorChanged/editor/EditorManager.js:182 _handleCurrentFileChange/utils/EventDispatcher.js:222 trigger/view/MainViewManager.js:1081 (anonymous function)/utils/EventDispatcher.js:222 trigger/view/Pane.js:729 Pane._notifyCurrentViewChange/view/Pane.js:1011 Pane.showView/editor/EditorManager.js:557 _showEditor/editor/EditorManager.js:627 openDocument/view/MainViewManager.js:1182 _edit/view/MainViewManager.js:1272 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)/document/DocumentManager.js:379 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)/file/FileUtils.js:82 (anonymous function)/filesystem/File.js:125 (anonymous function)/filesystem/impls/appshell/AppshellFileSystem.js:378 (anonymous function)
/utils/EventDispatcher.js:225 Assertion failed:/utils/EventDispatcher.js:225 trigger/editor/EditorManager.js:165 _notifyActiveEditorChanged/editor/EditorManager.js:182 _handleCurrentFileChange/utils/EventDispatcher.js:222 trigger/view/MainViewManager.js:1081 (anonymous function)/utils/EventDispatcher.js:222 trigger/view/Pane.js:729 Pane._notifyCurrentViewChange/view/Pane.js:1011 Pane.showView/editor/EditorManager.js:557 _showEditor/editor/EditorManager.js:627 openDocument/view/MainViewManager.js:1182 _edit/view/MainViewManager.js:1272 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)/document/DocumentManager.js:379 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)/file/FileUtils.js:82 (anonymous function)/filesystem/File.js:125 (anonymous function)/filesystem/impls/appshell/AppshellFileSystem.js:378 (anonymous function)

**Comment by deniuscoder** [comment]
I saw the whole thing in the Brackets.1.2.
I installed Brackets.1.1.Extract and everything was working steadily

**Comment by deniuscoder** [comment]
It looks like a conflict with Emmet
after it is installed, you get this error

**Comment by deniuscoder** [comment]
now precisely understood,
when I was doing my snippets
as pointed out in the description - $ ('') or .css('{}') apparently when loading the module were not screened these descriptions and it turned into a bug
after I removed from the description of these signs ($,., {}) all work is restored!
I think you should release an update to fix this bug

**Comment by chuyik** [comment]
Thanks for the report, I've tried to create some snippets and filled in the descriptions with the signs you mentioned, and also restart the app, but still no errors.

![image](https://cloud.githubusercontent.com/assets/6262943/6501412/07891eae-c353-11e4-888b-9c1f6b537404.png)

And I'm also using Emmet as well, so I don't think there're any relevances with it.
