### ISSUE TITLE
New error, not running. this is the error

### ISSUE THREAD

**Issue by Jonatthu** [chuyik/brackets-snippets#35]
Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at Object.<anonymous> (file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:4:3)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at Object.<anonymous> (file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:656:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at Object.<anonymous> (file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:656:17)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:47:18
    at Function.CodeMirror.getMode (/thirdparty/CodeMirror2/lib/codemirror.js:4734:19)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:614:27
    at Object.<anonymous> (file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:656:4)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:49:5
    at Function.CodeMirror.getMode (/thirdparty/CodeMirror2/lib/codemirror.js:4734:19)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:614:27
    at Object.<anonymous> (file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade/main.js:656:4)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/garthdb.brackets-stylus/stylus.js:8:1
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/garthdb.brackets-stylus/stylus.js:758:1
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:121:32)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/garthdb.brackets-stylus/stylus.js:759:1
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:123:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:124:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.eval (/./ParfaitAPI.js:125:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at file:///C:/Users/Jonatthu/AppData/Roaming/Brackets/extensions/user/jade-snippets/main.js:103:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.registerMainPanel (/./MainPanel.js:285:9)
    at _appReadyHandler (/main.js:281:19)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object._initParfaitControlsPopup [as initParfaitControlsPopup] (/./ParfaitPopup.js:112:9)
    at _appReadyHandler (/main.js:282:22)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:285:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _attachExtensionManagerListener (/main.js:118:9)
    at _appReadyHandler (/main.js:289:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _setupAbandonmentEvents (/main.js:234:9)
    at _appReadyHandler (/main.js:291:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:294:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)

**Comment by chuyik** [comment]
Hi @Jonatthu, I notice there has nothing to do with my extension in the error logs you provide, would you like to uninstall(or disable) other extensions to avoid some unknown conflicts?

**Comment by chuyik** [comment]
Close for not response, feel free to reopen.
